# One Discipline: Two Paradigms




### Symbolic AI
<img style="float:right;" src="figs/mind.png">

Inspired by ideas of the mind and  building on thousands of years of philosophy about:

- what can be known,  
world models, absolute truths
- types of logic, 
- facts, rules, ...

Reasoning with symbols that 'stand for' external entities or 'truths'.
 - this was mainstream AI for decades


### Computational AI: 
<img style="float: right;" src="figs/brain.jpg">

Inspired by the idea of problem solving arising from  computational processes 
- the brain   
  - a neural signal processor  
    with adaptive connections
- Genetics + Darwinian evolution 
- Social Insect Colonies

All _appear_ to exhibit intelligent problem solving behaviour

 

# How would you describe these three types of fruit?


  
</div><div height = 50%>
    <div width=25% style="float:left">  <img style="width:100px" src="./figs/green_apple.jpg" alt="Picture of an apple"/>   </div>
    <div width=25% style="float:centre">  <img style="width:100px" src="./figs/banana.jpg" alt="Picture of a banana"/>   </div>
        <div width=25% >  <img  style="width:100px" src="./figs/orange.jpg" alt="Picture of an orange" style="float:right"/>   </div>
</div>  

Many people might say:
- Apples are green and round and have smooth skin
- Oranges are orange and round and have rough skin
- Bananas are yellow and long and pointed at both ends and have smooth skin. 

## Symbolic AI says that these are all examples of an abstract class 
e.g. 'Apples', 'Oranges' or 'Bananas'.

To reason about them we make statements in a 'world-model' that are True or False for things of that type
 - A **Model** encoding human expertise is often  called the **'knowledge base'**

A mixture of **Facts**

|          | Apples | Oranges | Bananas |
|----------|--------|---------|---------|
| isGreen  | True   |         |         |
| IsOrange |        | True    |         |
| isYellow |        |         | True    |
| isRound  | True   | True    |         |
| isLong   |        |         | True    |
| isRough  |        | True    |         |
| isSmooth | True   |         | True    |

 And  **logic**   

usually **Rules** that we can apply to generate new facts  

_isRound(x)_ AND _isGreen(x)_  AND _isSmooth(x)_   => _isApple(x)_

_isRound(x)_ AND _isOrange(x)_ AND _isRough(x)_    => _isOrange(x)_

_isLong(x)_  AND _isYellow(x)_ AND _isSmooth(x)_   => _isBanana(x)_

## Using a symbolic AI model for prediction

 <img style="float:right" src = "figs/lime.jpg">
 
1. Create the **model** by encoding this knowledge  using rules in your chosen type of  logic 
 


 
2. provide **input** in the form of 'assertions' about a new bit of fruit
 - _isRound(newfruit)_ = True
 - _isGreen(newfruit)_ = True
 
 
3. Make a **prediction** by applying logic (deduction) to infer the _**output**_ 
 - _isApple(newfruit)_ = False

## How does this work in the real world?
1. Decide on a set of features you can measure about objects, for example:
 - weight in grammes
 - height/width in cm
 - mean RGB values of image

2. Measure values of those features for a set of examples
 - store these in a Dataset (e.g. numpy 2D array).
 - one row per example,
 - one column for each feature 
 - one column for the label (orange/apple/banana)  
  or put the label in a separate array

**Colour**     (from www.colorhexa.com)
-    In a RGB color space, hex #ffe135 (also known as Banana yellow) is composed of 100% red, 88.2% green and 20.8% blue. 
-    In a RGB color space, hex #8db600 (also known as Apple green) is composed of 55.3% red, 71.4% green and 0% blue.
-    In a RGB color space, hex #ffa500 (also known as Orange) is composed of 100% red, 64.7% green and 0% blue.
    
**Size** from quick search on internet (using the _'are sites consistent?'_ heuristic)
-    banana: width 130 +/- 15 mm height 28 +/- 05 cm, weight 125 +/- 10 gm
- apple    width = height = 80mm  +/-    weight = 340 g
- orange   width = height = 76mm   +/-   weight = 357 g
    
    

````
# values ( mean_red, mean_green, mean_blue,width, height, weight)
typical_banana = (100,88.2,20.8,130,28,125 )
typical_apple = (55.3,71.4,0,80,80,340)
typical_orange = (100,64.7,0,76,76,357)
````

# Make some fake data
 Unless you each have thre pieces of fruit with you?

### We'll use a function built into sklearn to create datasets
It takes the 'ideal' values then adds small amounts of noise

In [1]:
import w1_utils, numpy as np, matplotlib.pyplot as plt
np.set_printoptions(precision=2)

feature_values,labels = w1_utils.makeFakeFruit()
for feats,label in zip(feature_values,labels):
    print (feats,label)

[101.26  62.18   5.42  75.6   74.45 354.2 ] orange
[ 47.63  68.07 -11.61  78.13  84.78 343.05] apple
[ 98.38  91.06  13.11 131.4   28.03 123.  ] banana
[108.09  72.91 -12.2   75.59  67.76 357.81] orange
[101.54  67.91  -8.1   79.92  72.81 347.9 ] orange
[ 57.32  66.63  10.13  75.41  80.09 344.77] apple
[5.32e+01 6.45e+01 3.09e-01 7.31e+01 8.33e+01 3.38e+02] apple
[ 96.77  62.92  -5.59  77.71  73.97 359.58] orange
[ 59.09  65.08  -1.28  83.61  73.98 352.82] apple
[ 99.12  91.62  15.6  133.91  27.75 119.43] banana
[ 96.62  65.49   5.58  79.29  77.42 360.19] orange
[ 57.56  65.12  -7.79  82.93  82.24 342.76] apple
[ 53.88  67.82  -2.6   74.71  81.92 335.98] apple
[ 98.8   91.21  22.37 122.7   25.55 116.38] banana
[100.99  87.72  25.79 135.09  32.15 120.3 ] banana
[ 96.2   93.4   33.76 129.05  28.94 123.51] banana
[ 99.84  83.05  18.74 133.35  14.25 127.04] banana
[ 87.2   65.14  -1.27  73.32  74.13 353.99] orange
[ 99.8   61.09   0.64  75.33  76.11 363.34] orange
[ 95.8   91.19  15.31 129

### We list our data and use matplotlib to create visualisations of what our data looks like

In [ ]:
fig = w1_utils.make3dscatters(feature_values,labels)
plt.show()

## Symbolic AI
Have to write code  that can:
 - extract meaning from these numerical features
 - to generate True/False for symbols like isLong() or isYellow()
 - those symbols are what used to do reasoning in the model

# Computational AI: 

- **Machine Learning**  creates models using algorithms that learn by trial and error from datasets (examples)
- **Heuristic Optimisation** takes a similar 'trial and error' approach to finding and improving solutions to optimisation problems

## Our fruit example

1. Get dataset of examples
2. **Apply an algorithm to find decision boundaries that separate the examples into classes**    
learned model = set of decision boundaries + labels for the regions they define
3. Make **prediction** by looking at where a new example is in relation to those boundaries

# Summary
## Two different approaches,  both with strengths and weaknesses
 1. Symbolic (Knowledge-based):
  - based on logic, facts and rules
  - uses a human-provided world model
 2. Computational AI
  - Algorithms that learn from experience
  - only as good as their experience
  

## Key Difference: 
In symbolic AI everything 'stands for' something in the real world.

- So you might write a function: Bool  isYellow( inr red, int green, int blue)
 - but it would be meangingless to pass values for width/height/weight into isYellow()
 - and the rules that define the 'fruit' model can't be used for anything else

In Computational AI 'everything is just numbers', 
- nothing has any special meaning
- so algorithms become more re-usable.

## You need to be able to: 
 - **Describe** the differences between these approaches
 - **Select** (and explain) whether to choose a computational or knowledge-based solution  
 to solve a given problem _in it's context_. 
 